server:
  port: 8989

share:
  now:
    car2go:
      Stuttgart:
        url: ${VEHICLE_ENDPOINT:http://host.docker.internal:3000/vehicles/Stuttgart}
      status:
        url: ${VEHICLE_ENDPOINT_STATUS:http://host.docker.internal:3000/status}
    polygon:
      url: https://gist.githubusercontent.com/codeofsumit/6540cdb245bd14c33b486b7981981b7b/raw/73ebda86c32923e203b2a8e61615da3e5f1695a2/polygons.json
    cache:
      refresh: ${CACHE_REFRESH_INTERVAL:300000}

spring:
  main:
    web-environment: true
  cache:
    names: cars
    type: none
    autoexpiry: true
    expire:
      delay: 30000
logging:
  level:
    org:
      springframework:
        cache: TRACE
org:
  springframework:
    cache:
      annotation:
        Cacheable: true
